<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $products = [
            [
                'slug' => 'HO001',
                'name' => 'Hoodie Nike Hitam',
                'price' => 150000,
                'image' => 'products/Hoodie Nike Hitam Size S.jpg',
                'images' => json_encode([
                    'products/Hoodie Nike Hitam Size S.jpg',
                ]),
                'sizes' => 'S',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Hoodie preloved original',
                'badge' => '',
                'category' => 'Hoodie',
            ],
            [
                'slug' => 'HO002',
                'name' => 'Hoodie Adidas Putih',
                'price' => 160000,
                'image' => 'products/Hoodie Adidas Putih Size M.jpg',
                'images' => json_encode([
                    'products/Hoodie Adidas Putih Size M.jpg',
                ]),
                'sizes' => 'M',
                'stock' => 1,
                'condition' => 'like_new',
                'description' => 'Hoodie preloved original',
                'badge' => '',
                'category' => 'Hoodie',
            ],
            [
                'slug' => 'HO003',
                'name' => 'Hoodie Uniqlo Abu',
                'price' => 170000,
                'image' => 'products/Hoodie Uniqlo Abu Size L.jpg',
                'images' => json_encode([
                    'products/Hoodie Uniqlo Abu Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'good',
                'description' => 'Hoodie preloved original',
                'badge' => '',
                'category' => 'Hoodie',
            ],
            [
                'slug' => 'HO004',
                'name' => 'Hoodie Champion Navy',
                'price' => 180000,
                'image' => 'products/Hoodie Champion Navy Size XL.jpg',
                'images' => json_encode([
                    'products/Hoodie Champion Navy Size XL.jpg',
                ]),
                'sizes' => 'XL',
                'stock' => 1,
                'condition' => 'fair',
                'description' => 'Hoodie preloved original',
                'badge' => '',
                'category' => 'Hoodie',
            ],
            [
                'slug' => 'HO005',
                'name' => 'Hoodie H&M Cream',
                'price' => 190000,
                'image' => 'products/Hoodie H&M Cream Size L.jpg',
                'images' => json_encode([
                    'products/Hoodie H&M Cream Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Hoodie preloved original',
                'badge' => '',
                'category' => 'Hoodie',
            ],

            [
                'slug' => 'KA001',
                'name' => 'Kaos Carhartt Abu',
                'price' => 200000,
                'image' => 'products/Kaos Carhartt Abu Size S.jpg',
                'images' => json_encode([
                    'products/Kaos Carhartt Abu Size S.jpg',
                ]),
                'sizes' => 'S',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Kaos preloved original',
                'badge' => '',
                'category' => 'Kaos',
            ],
            [
                'slug' => 'KA002',
                'name' => 'Kaos Uniqlo Navy',
                'price' => 210000,
                'image' => 'products/Kaos Uniqlo Navy Size M.jpg',
                'images' => json_encode([
                    'products/Kaos Uniqlo Navy Size M.jpg',
                ]),
                'sizes' => 'M',
                'stock' => 1,
                'condition' => 'like_new',
                'description' => 'Kaos preloved original',
                'badge' => '',
                'category' => 'Kaos',
            ],
            [
                'slug' => 'KA003',
                'name' => 'Kaos Nike Cream',
                'price' => 220000,
                'image' => 'products/Kaos Nike Cream Size L.jpg',
                'images' => json_encode([
                    'products/Kaos Nike Cream Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'good',
                'description' => 'Kaos preloved original',
                'badge' => '',
                'category' => 'Kaos',
            ],
            [
                'slug' => 'KA004',
                'name' => 'Kaos Polo Ralph Lauren Hijau',
                'price' => 230000,
                'image' => 'products/Kaos Polo Ralph Lauren Hijau Size XL.jpg',
                'images' => json_encode([
                    'products/Kaos Polo Ralph Lauren Hijau Size XL.jpg',
                ]),
                'sizes' => 'XL',
                'stock' => 1,
                'condition' => 'fair',
                'description' => 'Kaos preloved original',
                'badge' => '',
                'category' => 'Kaos',
            ],
            [
                'slug' => 'KA005',
                'name' => 'Kaos Vans Merah',
                'price' => 240000,
                'image' => 'products/Kaos Vans Merah Size L.jpg',
                'images' => json_encode([
                    'products/Kaos Vans Merah Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Kaos preloved original',
                'badge' => '',
                'category' => 'Kaos',
            ],

            [
                'slug' => 'KE001',
                'name' => 'Kemeja Uniqlo Cream',
                'price' => 250000,
                'image' => 'products/Kemeja Uniqlo Cream Size S.jpg',
                'images' => json_encode([
                    'products/Kemeja Uniqlo Cream Size S.jpg',
                ]),
                'sizes' => 'S',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Kemeja preloved original',
                'badge' => '',
                'category' => 'Kemeja',
            ],
            [
                'slug' => 'KE002',
                'name' => 'Kemeja Levis Hijau',
                'price' => 260000,
                'image' => 'products/Kemeja Levis Hijau Size M.jpg',
                'images' => json_encode([
                    'products/Kemeja Levis Hijau Size M.jpg',
                ]),
                'sizes' => 'M',
                'stock' => 1,
                'condition' => 'like_new',
                'description' => 'Kemeja preloved original',
                'badge' => '',
                'category' => 'Kemeja',
            ],
            [
                'slug' => 'KE003',
                'name' => 'Kemeja Zara Merah',
                'price' => 270000,
                'image' => 'products/Kemeja Zara Merah Size L.jpg',
                'images' => json_encode([
                    'products/Kemeja Zara Merah Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'good',
                'description' => 'Kemeja preloved original',
                'badge' => '',
                'category' => 'Kemeja',
            ],
            [
                'slug' => 'KE004',
                'name' => 'Kemeja Muji Biru',
                'price' => 280000,
                'image' => 'products/Kemeja Muji Biru Size XL.jpg',
                'images' => json_encode([
                    'products/Kemeja Muji Biru Size XL.jpg',
                ]),
                'sizes' => 'XL',
                'stock' => 1,
                'condition' => 'fair',
                'description' => 'Kemeja preloved original',
                'badge' => '',
                'category' => 'Kemeja',
            ],
            [
                'slug' => 'KE005',
                'name' => 'Kemeja H&M Olive',
                'price' => 290000,
                'image' => 'products/Kemeja H&M Olive Size L.jpg',
                'images' => json_encode([
                    'products/Kemeja H&M Olive Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Kemeja preloved original',
                'badge' => '',
                'category' => 'Kemeja',
            ],

            [
                'slug' => 'CE001',
                'name' => 'Celana Levis merah',
                'price' => 300000,
                'image' => 'products/Celana Levis merah Size S.jpg',
                'images' => json_encode([
                    'products/Celana Levis merah Size S.jpg',
                ]),
                'sizes' => 'S',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Celana preloved original',
                'badge' => '',
                'category' => 'Celana',
            ],
            [
                'slug' => 'CE002',
                'name' => 'Celana Dickies Biru',
                'price' => 310000,
                'image' => 'products/Celana Dickies Biru Size M.jpg',
                'images' => json_encode([
                    'products/Celana Dickies Biru Size M.jpg',
                ]),
                'sizes' => 'M',
                'stock' => 1,
                'condition' => 'like_new',
                'description' => 'Celana preloved original',
                'badge' => '',
                'category' => 'Celana',
            ],
            [
                'slug' => 'CE003',
                'name' => 'Celana Uniqlo Olive',
                'price' => 320000,
                'image' => 'products/Celana Uniqlo Olive Size L.jpg',
                'images' => json_encode([
                    'products/Celana Uniqlo Olive Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'good',
                'description' => 'Celana preloved original',
                'badge' => '',
                'category' => 'Celana',
            ],
            [
                'slug' => 'CE004',
                'name' => 'Celana Nike Beige',
                'price' => 330000,
                'image' => 'products/Celana Nike Beige Size XL.jpg',
                'images' => json_encode([
                    'products/Celana Nike Beige Size XL.jpg',
                ]),
                'sizes' => 'XL',
                'stock' => 1,
                'condition' => 'fair',
                'description' => 'Celana preloved original',
                'badge' => '',
                'category' => 'Celana',
            ],
            [
                'slug' => 'CE005',
                'name' => 'Celana Adidas Hitam',
                'price' => 340000,
                'image' => 'products/Celana Adidas Hitam Size L.jpg',
                'images' => json_encode([
                    'products/Celana Adidas Hitam Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Celana preloved original',
                'badge' => '',
                'category' => 'Celana',
            ],

            [
                'slug' => 'JA001',
                'name' => 'Jaket The North Face Olive',
                'price' => 200000,
                'image' => 'products/Jaket The North Face Olive Size S.jpg',
                'images' => json_encode([
                    'products/Jaket The North Face Olive Size S.jpg',
                ]),
                'sizes' => 'S',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Jaket preloved original',
                'badge' => '',
                'category' => 'Jaket',
            ],
            [
                'slug' => 'JA002',
                'name' => 'Jaket Nike Beige',
                'price' => 250000,
                'image' => 'products/Jaket Nike Beige Size M.jpg',
                'images' => json_encode([
                    'products/Jaket Nike Beige Size M.jpg',
                ]),
                'sizes' => 'M',
                'stock' => 1,
                'condition' => 'like_new',
                'description' => 'Jaket preloved original',
                'badge' => '',
                'category' => 'Jaket',
            ],
            [
                'slug' => 'JA003',
                'name' => 'Jaket Adidas Hitam',
                'price' => 200000,
                'image' => 'products/Jaket Adidas Hitam Size L.jpg',
                'images' => json_encode([
                    'products/Jaket Adidas Hitam Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'good',
                'description' => 'Jaket preloved original',
                'badge' => '',
                'category' => 'Jaket',
            ],
            [
                'slug' => 'JA004',
                'name' => 'Jaket Levis Putih',
                'price' => 220000,
                'image' => 'products/Jaket Levis Putih Size XL.jpg',
                'images' => json_encode([
                    'products/Jaket Levis Putih Size XL.jpg',
                ]),
                'sizes' => 'XL',
                'stock' => 1,
                'condition' => 'fair',
                'description' => 'Jaket preloved original',
                'badge' => '',
                'category' => 'Jaket',
            ],
            [
                'slug' => 'JA005',
                'name' => 'Jaket Champion Abu',
                'price' => 250000,
                'image' => 'products/Jaket Champion Abu Size L.jpg',
                'images' => json_encode([
                    'products/Jaket Champion Abu Size L.jpg',
                ]),
                'sizes' => 'L',
                'stock' => 1,
                'condition' => 'new',
                'description' => 'Jaket preloved original',
                'badge' => '',
                'category' => 'Jaket',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
